openapi: 3.0.0
info:
  title: Express TypeScript API
  version: 1.0.0
  description: An Express API with TypeScript for handling messages

servers:
  - url: http://localhost:{port}/api
    variables:
      port:
        default: '3000'

paths:
  /messages/public:
    get:
      summary: Get public message
      tags:
        - messages
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /messages/protected:
    get:
      summary: Get protected message
      tags:
        - messages
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized

  /messages/admin:
    get:
      summary: Get admin message
      tags:
        - messages
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized

components:
  schemas:
    Message:
      type: object
      properties:
        text:
          type: string
      required:
        - text

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
